replicaCount: 1

revisionHistoryLimit: 2

labels:
  environment: development

image:
  repository: ghcr.io/leooamaral/node-tracker
  tag: latest
  pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8081
    initialDelaySeconds: 15
    periodSeconds: 20
  readinessProbe:
    httpGet:
      path: /readyz
      port: 8081
    initialDelaySeconds: 5
    periodSeconds: 10

serviceAccount:
  create: true

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

deleteCRDOnUninstall: true