# permissions for end users to view gputrackers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gputracker-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gpu-tracker-operator
    app.kubernetes.io/part-of: gpu-tracker-operator
    app.kubernetes.io/managed-by: kustomize
  name: gputracker-viewer-role
rules:
- apiGroups:
  - suse.tests.dev
  resources:
  - gputrackers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - suse.tests.dev
  resources:
  - gputrackers/status
  verbs:
  - get
