name: Build and Publish Docker Image

on:
   push:
    #  branches:
    #    - master
    #  paths-ignore:
    #    - deploy/charts/**
env:
    REGISTRY: ghcr.io
    REGISTRY_IMAGE: ${{ github.repository_owner }}/gpu-tracker-operator
jobs:
  build:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        architecture:
          - amd64
          - arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REGISTRY_IMAGE }}

      - name: Build Docker Container
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/${{ matrix.architecture }}
          labels: ${{ steps.meta.outputs.labels}}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          build-args: |
            TARGETOS=linux
            TARGETARCH=${{ matrix.architecture }}

    #   - name: Generate Artifact Attestation
    #     uses: actions/attest-build-provenance@v2
    #     with:
    #       subject-name: ${{ env.REGISTRY }}/${{ env.REGISTRY_IMAGE }}
    #       subject-digest: ${{ steps.push.outputs.digest }}
    #       push-to-registry: true

    #   - name: Export digest
    #     run: |
    #       mkdir -p ${{ runner.temp }}/digests
    #       digest="${{ steps.push.outputs.digest }}"
    #       touch "${{ runner.temp }}/digests/${digest#sha256:}"
    #   - name: Upload digest
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: digests-linux-${{ matrix.architecture }}
    #       path: ${{ runner.temp }}/digests/*
    #       if-no-files-found: error
    #       retention-days: 1

    #   - name: Build and Push Image to GHCR [amd64]
    #     run: |
    #       docker build -t ghcr.io/leooamaral/gpunode-tracker:0.1.0 \
    #        --build-arg TARGETOS=linux --build-arg TARGETARCH=amd64 .

    #       docker push ghcr.io/leooamaral/gpunode-tracker:0.1.0
